# Generated by Django 4.0.3 on 2022-04-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_players'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.AddField(
            model_name='nba',
            name='players',
            field=models.ManyToManyField(to='main_app.player'),
        ),
    ]
