# Generated by Django 4.0.3 on 2022-04-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_players_player_nba_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('Point Guard', 'point guard'), ('Shooting Guard', 'shooting guard'), ('Small Forward', 'small forward'), ('Power Forward', 'power forward'), ('Center', 'center')], max_length=50),
        ),
    ]
