# Generated by Django 4.0.3 on 2022-04-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_nba_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='img',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='time_line',
            field=models.CharField(choices=[('Point Guard', 'point guard'), ('Shooting Guard', 'shooting guard'), ('Small Forward', 'small forward'), ('Power Forward', 'power forward'), ('Center', 'center')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
