# Generated by Django 4.0.3 on 2022-04-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_player_img_player_time_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='time_line',
            field=models.CharField(choices=[('Current', 'current'), ('Past', 'Past')], max_length=50),
        ),
    ]
